// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Message(Props) {
  var text = Props.text;
  var type_ = Props.type_;
  var className = type_ ? "message--error" : "message--info";
  return React.createElement("div", {
              className: className
            }, text);
}

var make = Message;

exports.make = make;
/* react Not a pure module */
