// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function RandomAdvice(Props) {
  var data = Props.data;
  return React.createElement("div", {
              className: "random-advice-container"
            }, React.createElement("div", {
                  className: "random-advice"
                }, data[/* value */1]));
}

var make = RandomAdvice;

exports.make = make;
/* react Not a pure module */
