// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Spinner(Props) {
  var showOpt = Props.show;
  var show = showOpt !== undefined ? showOpt : false;
  return React.createElement("div", {
              className: "spinner-container"
            }, show ? React.createElement("div", {
                    className: "spinner"
                  }) : null);
}

var make = Spinner;

exports.make = make;
/* react Not a pure module */
