// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var Root$ReactHooksTemplate = require("./router/Root.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Root$ReactHooksTemplate.make, {}), "root");

/*  Not a pure module */
