// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function debugLog(v) {
  if (typeof v === "number") {
    return "Not Asked";
  } else {
    switch (v.tag | 0) {
      case /* Loading */0 :
          var s = Belt_List.toArray(v[0]).join(", ");
          return "Loading (" + (String(s) + ")");
      case /* Failure */1 :
          return "Failure";
      case /* Success */2 :
          var s$1 = Belt_List.toArray(v[0]).join(" + ");
          return "Success (" + (String(s$1) + ")");
      
    }
  }
}

console.log("Not Asked");

console.log("Not Asked");

console.log(debugLog(/* Loading */Block.__(0, [/* :: */[
              "foo",
              /* :: */[
                "bar",
                /* [] */0
              ]
            ]])));

console.log(debugLog(/* Success */Block.__(2, [/* :: */[
              "foo",
              /* :: */[
                "bar",
                /* :: */[
                  "baz",
                  /* [] */0
                ]
              ]
            ]])));

console.log("Failure");

exports.debugLog = debugLog;
/*  Not a pure module */
