// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function debugLog(v) {
  if (typeof v === "number") {
    return "Not Asked";
  }
  switch (v.TAG | 0) {
    case /* Loading */0 :
        var s = Belt_List.toArray(v._0).join(", ");
        return "Loading (" + s + ")";
    case /* Failure */1 :
        return "Failure";
    case /* Success */2 :
        var s$1 = Belt_List.toArray(v._0).join(" + ");
        return "Success (" + s$1 + ")";
    
  }
}

console.log("Not Asked");

console.log("Not Asked");

console.log(debugLog({
          TAG: /* Loading */0,
          _0: {
            hd: "foo",
            tl: {
              hd: "bar",
              tl: /* [] */0
            }
          }
        }));

console.log(debugLog({
          TAG: /* Success */2,
          _0: {
            hd: "foo",
            tl: {
              hd: "bar",
              tl: {
                hd: "baz",
                tl: /* [] */0
              }
            }
          }
        }));

console.log("Failure");

exports.debugLog = debugLog;
/*  Not a pure module */
