// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var RemoteData = require("remotedata-re/src/RemoteData.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function toLoading(data) {
  return /* Loading */Block.__(0, [RemoteData.withDefault(undefined, RemoteData.map((function (d) {
                        return Caml_option.some(d);
                      }), data))]);
}

function updateWebData(data, action) {
  if (typeof action === "number") {
    return toLoading(data);
  } else if (action.tag) {
    return /* Success */Block.__(2, [action[0]]);
  } else {
    return /* Failure */Block.__(1, [action[0]]);
  }
}

exports.toLoading = toLoading;
exports.updateWebData = updateWebData;
/* No side effect */
