// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var RemoteData = require("remotedata-re/src/RemoteData.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function toLoading(data) {
  return {
          TAG: /* Loading */0,
          _0: RemoteData.withDefault(undefined, RemoteData.map((function (d) {
                      return Caml_option.some(d);
                    }), data))
        };
}

function updateWebData(data, action) {
  if (typeof action === "number") {
    return toLoading(data);
  } else if (action.TAG === /* RequestError */0) {
    return {
            TAG: /* Failure */1,
            _0: action._0
          };
  } else {
    return {
            TAG: /* Success */2,
            _0: action._0
          };
  }
}

exports.toLoading = toLoading;
exports.updateWebData = updateWebData;
/* No side effect */
