// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function routeToPath(route) {
  switch (route) {
    case /* RandomOnly */0 :
        return "random";
    case /* Home */1 :
        return "home";
    case /* NotFound */2 :
        return "";
    
  }
}

function routeToUrl(route) {
  switch (route) {
    case /* RandomOnly */0 :
        return "/random";
    case /* Home */1 :
        return "/home";
    case /* NotFound */2 :
        return "/";
    
  }
}

function useAppUrl(param) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "home" :
          if (match[1]) {
            return /* NotFound */2;
          } else {
            return /* Home */1;
          }
      case "random" :
          if (match[1]) {
            return /* NotFound */2;
          } else {
            return /* RandomOnly */0;
          }
      default:
        return /* NotFound */2;
    }
  } else {
    return /* Home */1;
  }
}

exports.routeToPath = routeToPath;
exports.routeToUrl = routeToUrl;
exports.useAppUrl = useAppUrl;
/* ReasonReactRouter Not a pure module */
