// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.bs.js");

function routeToPath(route) {
  switch (route) {
    case /* RandomOnly */0 :
        return "random";
    case /* Home */1 :
        return "home";
    case /* NotFound */2 :
        return "";
    
  }
}

function routeToUrl(route) {
  switch (route) {
    case /* RandomOnly */0 :
        return "/random";
    case /* Home */1 :
        return "/home";
    case /* NotFound */2 :
        return "/";
    
  }
}

function useAppUrl(param) {
  var url = ReasonReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return /* Home */1;
  }
  switch (match.hd) {
    case "home" :
        if (match.tl) {
          return /* NotFound */2;
        } else {
          return /* Home */1;
        }
    case "random" :
        if (match.tl) {
          return /* NotFound */2;
        } else {
          return /* RandomOnly */0;
        }
    default:
      return /* NotFound */2;
  }
}

exports.routeToPath = routeToPath;
exports.routeToUrl = routeToUrl;
exports.useAppUrl = useAppUrl;
/* ReasonReactRouter Not a pure module */
